draft version of introduction to addon in korean
Korean-Translation-2022/learnstorybook.com pull request #10
Opened 2022-02-06 11:08 UTC by 1myourman

2022-02-06 11:29 UTC, MiryangJung commented on content/create-an-addon/react/ko/introduction.md
> +당신의 CSS 레이아웃이 디자인과 맞는 지에 대해 확언하는 것은 어렵다. Eyeballing alignment은 미묘할 수 있다. DOM elements가 멀리 떨어져 있거나 이상한 모양을 가지고 있으면 말이다.
Eyeballing alignment 도 번역해야 매끄러울 듯합니다.

2022-02-06 11:29 UTC, MiryangJung commented on content/create-an-addon/react/ko/introduction.md
> +Addons는 세가지 타입의 인터페이스 엘리멘트를 만들 수 있다:
엘리멘트 이 것도 영어로 그냥 표현할지 논의가 필요하겠네요.

2022-03-12 09:56 UTC, 1myourman commented
@[0westo](https://github.com/0westo) 리뷰 부탁드릴게요, 닫지 않고 그대로 두었습니다.

2022-03-13 12:21 UTC, lisohh commented on content/create-an-addon/react/ko/introduction.md
> +Addons는 세가지 타입의 인터페이스 엘리멘트를 만들 수 있다:
엘리먼트로 바꿔주세요~

2022-03-13 12:37 UTC, pak-fuse commented on content/create-an-addon/react/ko/setup.md
> +이 명령어는 모든 코드를 JS로 변형해줄 겁니다. 파괴적일 수 있는 과정이라, 이 명령어를 다른 어느 코드 작성을 시작하기전에 먼저 실행하기를 추천합니다.
여기서 JS로 변경한다는 것이 파일 형식을 JS로 변형해준다는 의미일까요? 파일형식이라도 JS로 쓰는 것보다 '자바스크립트'로 쓰는 게 어떨까 싶어요 ~

2022-03-13 12:37 UTC, pak-fuse commented on content/create-an-addon/react/ko/setup.md
> +애드온 코드는 'src' 디렉토리에 살고 있습니다. 포함된 보일러플레이트 코드는 세개의 UI 패러다임과 다른 개념들, 예를 들어 상태 관리나 스토리에 반응하기 등을 보여주고 있습니다. 다음 섹션에서 이것들을 세세하게 다룰 것입니다.
살고 있습니다. 는 약간 어색하게 느껴져서 위치 합니다. 와 같은 표현은 어떨까요?

2022-03-13 12:37 UTC, pak-fuse commented on content/create-an-addon/react/ko/introduction.md
> +<div class="aside">본 가이드는 스토리북 애드온을 구축하고자 하는 <b>프로페셔널한 개발자</b>들을 위해 작성되었습니다. 중급 이상의 자바스크립트나 리액트에 대한 경험이 필요합니다. 스토리북에 대한 기본 개념 역시 알아야 하는데, 그 예로는 스토리를 쓴다거나 환경설정(config)을 쓰는 방법 등이 있습니다. (<a href="/intro
'스토리북'이라고 하신 부분은 'Storybook'으로 변환해주셨으면 해요-!

2022-03-13 12:39 UTC, pak-fuse commented on content/create-an-addon/react/ko/track-state.md
> +리액트는 [hooks](https://reactjs.org/docs/hooks-state.html#gatsby-focus-wrapper) 로 만들어졌고 그 예로는 state를 관리하기 위한 `useState`이 있습니다. 보통은 이것으로 충분합니다만, 이 경우에는 조금 복잡합니다. 잠시 스토리북이 어떻게 구축되어 있는지를 이야기 해보겠습니다.
state -> 상태(state) 면 어떨까요

2022-03-13 12:39 UTC, pak-fuse commented on content/create-an-addon/react/ko/track-state.md
> +겉으로 보기에는 스토리북은 통일화된 유저 인터페이스를 보여줍니다. 그러나 안에서는, 두 세그먼트로 나뉘어져, **커뮤니케이션 채널을 통해서 이야기를 나눕니다:**
유저 인터페이스 -> 유저 인터페이스(UI)

2022-03-13 12:39 UTC, pak-fuse commented on content/create-an-addon/react/ko/track-state.md
> +The Addon Kit preconfigures the `Tool` to use globals. Let’s rename the global to more accurately reflect what it does. The `toggleOutline` function allows the user to actually toggle the outline add
이 부분은 번역을 덜 하신걸까요?

2022-03-13 12:43 UTC, lisohh requested changes

2022-03-13 12:43 UTC, lisohh commented on content/create-an-addon/react/ko/introduction.md
> +CSS 레이아웃이 디자인과 맞는지에 대해 확언하는 것은 어려운 일입니다. 눈대중적 줄맞춤은 미묘할 수 있습니다. 특히나 DOM 엘리먼트가 멀리 떨어져 있거나 이상한 모양을 가지고 있다면 말입니다.
'눈대중적 줄맞춤'이 조금 어색한데 '눈대중으로 하는 정렬'은 어떨까요?

2022-03-13 12:43 UTC, lisohh commented on content/create-an-addon/react/ko/introduction.md
> +[아웃라인 애드온](https://storybook.js.org/addons/storybook-addon-outline) 아웃라인 애드온은 CSS를 이용해서 UI 엘리먼트의 아웃라인을 잡는 툴바 버튼을 더하고 있습니다. 이것은 포지셔닝이나 자리 배치에 대한 것들을 한눈에 쉽게 하도록 도와줍니다. 아래 예제를 살펴보세요.
Outline 단어를 어떻게 쓸 지 의논할 필요가 있네요.. 여러 멤버분들이 다양하게 작성해주셔서요

2022-03-13 12:43 UTC, lisohh commented on content/create-an-addon/react/ko/introduction.md
> +2. [액션 애드온](https://storybook.js.org/docs/react/essentials/actions) 을 닮은 애드온은 판넬을 만들 수 있습니다. 현황 일지를 배치할 수 있습니다.
판넬 -> 패널로 통일할게요~

2022-03-13 12:43 UTC, lisohh commented on content/create-an-addon/react/ko/introduction.md
> +2. [액션 애드온](https://storybook.js.org/docs/react/essentials/actions) 을 닮은 애드온은 판넬을 만들 수 있습니다. 현황 일지를 배치할 수 있습니다.
현황 일지를 배치할 수 있습니다.가 혹시 어떤 문장을 번역하신 건가요?

2022-03-13 12:43 UTC, lisohh commented on content/create-an-addon/react/ko/introduction.md
> +3. 새로운 탭을 만듭니다. [스토리북 문서](https://storybook.js.org/docs/react/writing-docs/introduction) 컴포넌트 문서화를 표시합니다.
표시합니다보다는 보여줍니다가 더 자연스러울 것 같아요.

2022-03-13 12:43 UTC, lisohh commented on content/create-an-addon/react/ko/setup.md
> +- 📦 트랜스파일링과 번들링을 [바벨]과 함께(http://babeljs.io/)
Babel과 밑의 Auto는 고유명사라서 그대로 영어로 써주시면 될 것 같습니다.

2022-03-13 12:43 UTC, lisohh commented on content/create-an-addon/react/ko/setup.md
> +- 🚢 릴리즈 관리를 [오토]와 함께(https://github.com/intuit/auto)
여기도 auto로 통일해주세요

2022-03-13 12:43 UTC, lisohh commented on content/create-an-addon/react/ko/setup.md
> +이 명령어는 모든 코드를 JS로 변형해줄 겁니다. 파괴적일 수 있는 과정이라, 이 명령어를 다른 어느 코드 작성을 시작하기전에 먼저 실행하기를 추천합니다.
파괴적일 수 있는 과정이라는 말이 어떤 뜻일까요? 조금 더 다듬으면 좋을 것 같아요~

2022-03-13 12:45 UTC, lisohh requested changes

2022-03-13 12:45 UTC, lisohh commented on content/create-an-addon/react/ko/Register addon.md
> +이 파일 `src/Tool.js` 에서 시작합시다. 이곳이 아웃라인 툴을 위한 UI 코드가 있을 곳입니다. 이 임포트를 [@storybook/components](https://www.npmjs.com/package/@storybook/components) 확인하세요. 스토리북의 컴포넌트 라이브러리이며, 리액트와 이모션으로 만들어져 있습니다. 스토리북을
'이 파일'은 지워도 될 것 같아요. 임포트는 그대로 import라고 써주세요~

2022-03-13 12:45 UTC, lisohh commented on content/create-an-addon/react/ko/Register addon.md
> +툴 역시도 고유한 아이디와 함께 등록합니다. 다음과 같은 이름을 추천드립니다 `storybook/addon-name`. 애드온 키트 역시 탭과 판넬 예시를 포함하고 있습니다. 아웃라인 애드온이 툴만을 사용하기 때문에, 나머지는 삭제합니다.
`storybook/addon-name`과 같은 이름을 추천드립니다. 가 좀 더 자연스러운 느낌이에요~

2022-03-13 12:53 UTC, lisohh requested changes

2022-03-13 12:53 UTC, lisohh commented on content/create-an-addon/react/ko/track-state.md
> +[Globals](https://storybook.js.org/docs/react/essentials/toolbars-and-globals/#globals) 는 “글로벌” (스토리에 국한된 것이 아닌) 컨텍스트를 스토리북에서 가집니다. 다른 스토리와 애드온과 데코레이터 사이에서 정보를 공유하기 편한 방법들입니다. `useGlobals` 훅은 이 글로벌 컨
글로벌은 전역으로 통일할게요~ “글로벌”을 "전역"으로 바꿔주심 되겠습니다.

2022-03-15 13:51 UTC, 1myourman commented on content/create-an-addon/react/ko/introduction.md
> +CSS 레이아웃이 디자인과 맞는지에 대해 확언하는 것은 어려운 일입니다. 눈대중적 줄맞춤은 미묘할 수 있습니다. 특히나 DOM 엘리먼트가 멀리 떨어져 있거나 이상한 모양을 가지고 있다면 말입니다.
'눈대중을 사용한 정렬' 은 어떨까요? 주신 의견도 좋습니다

2022-03-15 13:52 UTC, 1myourman commented on content/create-an-addon/react/ko/setup.md
> +이 명령어는 모든 코드를 JS로 변형해줄 겁니다. 파괴적일 수 있는 과정이라, 이 명령어를 다른 어느 코드 작성을 시작하기전에 먼저 실행하기를 추천합니다.
destructive process라는데 이거는 잘 모르겠습니다~ 많은 게 바뀔 수 있는 크리티컬한 상태를 말하는 것 같은데

2022-03-15 14:17 UTC, 1myourman commented on content/create-an-addon/react/ko/introduction.md
> +2. [액션 애드온](https://storybook.js.org/docs/react/essentials/actions) 을 닮은 애드온은 판넬을 만들 수 있습니다. 현황 일지를 배치할 수 있습니다.
Create an addon Panel similar to the [Actions addon](https://storybook.js.org/docs/react/essentials/actions) which displays a log of actions 입니다

2022-03-19 08:41 UTC, merged