ui-testing-handbook - introduction
Korean-Translation-2022/learnstorybook.com pull request #11
Opened 2022-02-06 12:05 UTC by perfumelim

2022-02-06 12:15 UTC, MiryangJung requested changes

2022-02-06 12:15 UTC, MiryangJung commented on content/ui-testing-handbook/react/ko/introduction.md
> +tocTitle: 'Introduction'
타이틀 번역이 필요합니다.

2022-02-06 12:15 UTC, MiryangJung commented on content/ui-testing-handbook/react/ko/introduction.md
> +In upcoming chapters, we'll dig deeper into each layer of the test stack and get into the mechanics implementing this testing strategy. But first, we’re going to need something to test. I’ll be using
영어부분 지우셔야해요.

2022-02-06 12:15 UTC, MiryangJung commented on content/ui-testing-handbook/react/ko/introduction.md
> +코드를 직접 보고 싶다면 이 repository https://github.com/chromaui/ui-testing-guide-code 를 fork한 다음, 아래의 커맨드를 따라하면 된다.
repository> 저장소가 더 나을 듯합니다.

2022-02-06 12:38 UTC, perfumelim commented on content/ui-testing-handbook/react/ko/introduction.md
> +In upcoming chapters, we'll dig deeper into each layer of the test stack and get into the mechanics implementing this testing strategy. But first, we’re going to need something to test. I’ll be using
감사합니다. 삭제했어요!

2022-02-06 15:21 UTC, MiryangJung approved these changes
LGTM!

2022-02-16 08:34 UTC, lisohh commented on content/ui-testing-handbook/react/ko/introduction.md
> +<!-- 이 위까지요 -->
선두적인 프론트엔드 팀을 어떻게 따라갈 수 있을까? -> 선두적인 프런트엔드 팀은 어떻게 뒤쳐지지 않을까? 혹은 어떻게 선두를 유지할까? 가 더 정확할 것 같아요.

2022-02-16 08:34 UTC, lisohh commented on content/ui-testing-handbook/react/ko/introduction.md
> -널리 사용되는 JavaScript 프레임워크는 모두 [컴포넌트 기반 (componet-driven)](https://www.componentdriven.org/) 으로 동작한다. 즉, UI는 가장 작은 단위인 Atomic 컴포넌트부터 시작해서 점진적으로 페이지가 되는 "bottom-up" 방식으로 구성된다.
이 문장 순서가 뒤의 질문 밑으로 와야할 것 같아요. 원문을 보니 순서가 바뀐것같아요?

2022-02-16 08:34 UTC, lisohh commented on content/ui-testing-handbook/react/ko/introduction.md
> -오늘날 UI를 구성하는 모든 조각이 컴포넌트라는 것을 기억하자. 물론 페이지도 마찬가지다. 페이지와 버튼의 차이점은 데이터를 소비하는 방식뿐이다.
이것도 위아래 문장 순서가 바뀐 것 같아요.

2022-02-16 08:34 UTC, lisohh commented on content/ui-testing-handbook/react/ko/introduction.md
> -오늘날 UI를 구성하는 모든 조각이 컴포넌트라는 것을 기억하자. 물론 페이지도 마찬가지다. 페이지와 버튼의 차이점은 데이터를 소비하는 방식뿐이다.
아 아래에 어투 바뀐게 있군요. 리뷰하기가 헷갈려서 원래 어투는 삭제하고 올려주시면 좋을 것 같아요! ㅠㅠ ㅎ

2022-02-16 08:35 UTC, lisohh commented
첫번째 문체로 번역한 내용은 다른 곳에 옮겨두시거나 지워서 commit해주시면 리뷰하기가 더 수월할 것 같아요. 계속 문장 순서가 헷갈리네요 ㅜ

2022-02-16 15:05 UTC, perfumelim commented on content/ui-testing-handbook/react/ko/introduction.md
> -널리 사용되는 JavaScript 프레임워크는 모두 [컴포넌트 기반 (componet-driven)](https://www.componentdriven.org/) 으로 동작한다. 즉, UI는 가장 작은 단위인 Atomic 컴포넌트부터 시작해서 점진적으로 페이지가 되는 "bottom-up" 방식으로 구성된다.
ㅠㅠ..?? file-changed를 보고 리뷰 달아주시는 게 아닌가요?? 이건 맨 처음에 회의 전에 pr했던 부분인데요

2022-02-16 15:06 UTC, perfumelim commented on content/ui-testing-handbook/react/ko/introduction.md
> -오늘날 UI를 구성하는 모든 조각이 컴포넌트라는 것을 기억하자. 물론 페이지도 마찬가지다. 페이지와 버튼의 차이점은 데이터를 소비하는 방식뿐이다.
기존 문장은 다 지웠는데 무슨 말씀을 하시는 건지 잘 모르겠습니당..!!!

2022-03-12 14:49 UTC, lisohh approved these changes
좋아용

2022-03-13 10:02 UTC, lisohh requested changes
composition-testing 리뷰했습니다. 확인해주세요 홍시님:)

2022-03-13 10:02 UTC, lisohh commented on content/ui-testing-handbook/react/ko/composition-testing.md
> +다음 챕터에서는 단순한 모양새 뿐만 아니라 인터렉션(interaction)을 테스트할 것입니다. 사용자가 완료한 일정을 체크했을 때, 적절한 이벤트가 발생하고 상태가 올바르게 업데이트되는지 어떻게 확인할 수 있을까요?
인터렉션 -> 인터랙션으로 변경해주세요 ~ 인터랙션이 표준 표기같아요우

2022-03-13 10:04 UTC, lisohh requested changes
단어 하나만 교체해주세요~

2022-03-13 10:04 UTC, lisohh commented on content/ui-testing-handbook/react/ko/introduction.md
> +- 🐙 [Jest](https://jestjs.io/)와 [Testing Library](https://testing-library.com/)를 이용한 **인터렉션 검증**.
인터렉션 -> 인터랙션으로 교체해주세용

2022-03-13 11:42 UTC, perfumelim commented on content/ui-testing-handbook/react/ko/composition-testing.md
> +args 구성을 통해 story를 형성하는 것은 아주 강력한 기술입니다. 이를 통해 동일한 데이터를 반복해서 적지 않아도 story를 작성할 수 있습니다. 더욱 놀라운 것은 컴포넌트를 통합적으로 테스트를 할 수 있다는 점입니다. 만약 `Task` 컴포넌트의 prop 중 하나의 이름을 바꾸면, `TaskList`에 대한 테스트 케이스가 실패하게 됩니다.
번역할 때  '더욱 중요한 것은'이 뭔가 문맥상 어색하게 느껴지더라고요 ㅎㅎ 기술이 얼마나 좋은지 설명하는 부분이라 더 직관적으로 "더욱 훌륭한 점은" 으로 바꾸어봤어요.. 뭐가 더 나을까요?

2022-03-13 11:43 UTC, perfumelim commented on content/ui-testing-handbook/react/ko/composition-testing.md
> +애플리케이션은 컴포넌트를 서로 연결하여 구축됩니다. 그렇기 때문에 엘리먼트 하나의 버그가 그 주변 전체에 영향을 미치기도 합니다. 예를 들어, prop의 이름을 바꾸는 것만으로 부모 컴포넌트에서 자식 컴포넌트로의 데이터 흐름이 중단될 수 있습니다. 혹은 잘못 스타일링된 엘리먼트 하나로 레이아웃 자체가 깨지기도 합니다.
"하나가" 한 문장에 두 번 반복되서 조금 어색하지 않을까요..?!

2022-03-13 11:44 UTC, perfumelim commented on content/ui-testing-handbook/react/ko/composition-testing.md
> +애플리케이션의 트리 같은 특성은 Task component의 변경사항이 상위 컴포넌트에 대한 테스트에서도 포착된다는 것을 의미합니다. 구성 테스트를 통해 수정한 내용의 모든 부수효과를 알 수 있습니다.
이 부분이 회귀에러에 관한 부분이라 잠재적인?보다는 부수효과가 맞다고 생각했어요

2022-03-13 12:23 UTC, perfumelim commented on content/ui-testing-handbook/react/ko/introduction.md
> +- 🐙 [Jest](https://jestjs.io/)와 [Testing Library](https://testing-library.com/)를 이용한 **인터렉션 검증**.
수정했습니다!

2022-03-13 12:54 UTC, lisohh commented on content/ui-testing-handbook/react/ko/composition-testing.md
> +애플리케이션은 컴포넌트를 서로 연결하여 구축됩니다. 그렇기 때문에 엘리먼트 하나의 버그가 그 주변 전체에 영향을 미치기도 합니다. 예를 들어, prop의 이름을 바꾸는 것만으로 부모 컴포넌트에서 자식 컴포넌트로의 데이터 흐름이 중단될 수 있습니다. 혹은 잘못 스타일링된 엘리먼트 하나로 레이아웃 자체가 깨지기도 합니다.
그럼 뒤에 있는 하나를 한 개로 하는 건 어떠세요?? ?_?

2022-03-13 13:23 UTC, lisohh commented on content/ui-testing-handbook/react/ko/composition-testing.md
> +![Task list는 4가지 상태를 가지고 있습니다: 디폴트일 때, 아무것도 없을 때, 로딩중일 때, 북마크 됐을 때](/ui-testing-handbook/task-list.png)
고정됐을때~

2022-03-13 13:25 UTC, lisohh approved these changes

2022-03-13 13:26 UTC, lisohh approved these changes

2022-03-13 13:27 UTC, merged