decorater.md/1차번역/장키
Korean-Translation-2022/learnstorybook.com pull request #19
Opened 2022-03-03 12:30 UTC by 0westo

파일 초벌 번역 추가

2022-03-12 03:13 UTC, 1myourman reviewed
애드온을 addon으로 표기했었는데 어떻게 할지 봐야겠네요. 우선 한글버전으로 편집하시면 좋을 것 같습니다.

2022-03-13 11:19 UTC, lisohh requested changes
수정 요청합니다~

2022-03-13 11:19 UTC, lisohh commented on content/create-an-addon/react/ko/decorators.md
> +commit: '0e7246a'
제목 부분도 다 번역해주세요~

2022-03-13 11:19 UTC, lisohh commented on content/create-an-addon/react/ko/decorators.md
> +[데코레이터](https://storybook.js.org/docs/react/writing-stories/decorators)는 story를 래핑하고 엑스트라 렌더링 기능을 추가합니다. 우리는 글로벌 아웃라인에 대응하고 CSS 인젝션을 처리하는 데코레이터를 만들 겁니다. 이것은 차례로 모든 HTML 엘리먼트 주위에 아웃라인을 그리는 것입니다.
wrap은 오늘 어떻게 번역할지 정해봐야겠네요~ 그리고 extra는 '추가'로 번역해주시면 될 것 같습니다.

2022-03-13 11:19 UTC, lisohh commented on content/create-an-addon/react/ko/decorators.md
> +이전 단계에서 `outlineActive` Global을 규정했고, 정리해 보세요! `useGlobals` 훅 을 사용하여 데코레이터에서 글로벌을 소비할 수 있습니다.
정리해 보세요!를 앞 문장과 좀 더 자연스럽게 이어지도록 바꾸면 좋을 것 같아요.
이전 단계에서 `outlineActive` Global을 규정했으니,이제 연결해 볼까요! 는 어떨까요?

2022-03-13 11:19 UTC, lisohh commented on content/create-an-addon/react/ko/decorators.md
> +[데코레이터](https://storybook.js.org/docs/react/writing-stories/decorators)는 story를 래핑하고 엑스트라 렌더링 기능을 추가합니다. 우리는 글로벌 아웃라인에 대응하고 CSS 인젝션을 처리하는 데코레이터를 만들 겁니다. 이것은 차례로 모든 HTML 엘리먼트 주위에 아웃라인을 그리는 것입니다.
injection을 뒤에서는 삽입이라고 번역한 게 있어서, 여기서도 삽입이라고 번역해주셔도 될 것 같아요. 이 단어도 다시 의논해보고 정해야겠네요

2022-03-13 11:19 UTC, lisohh commented on content/create-an-addon/react/ko/decorators.md
> +스타일 추가 및 클리어는 부작용이기 때문에 이 작업을 `useEffect`에서 wrap해야 합니다. 다음으로 `outlineActive` global에 의해 트리거됩니다. Kit 코드에는 예시가 포함되어 있는데, outline CSS 인젝션을 처리하도록 업데이트 해보세요.
클리어 -> 삭제로 바꾸는게 더 매끄러울 것 같아요. 
첫문장이 어떤 의미인지 잘 감이 안오네요..
다음으로 `outlineActive` global에 의해 트리거됩니다. 요 문장도 좀 더 다듬으면 좋겠네요!

2022-03-13 11:19 UTC, lisohh commented on content/create-an-addon/react/ko/decorators.md
> +이를 통해 UI 엘리먼트 주위에 outline을 그릴 수 있습니다.
outline도 이 글안에서 여러 단어로 번역이 되어서 의논해보고 하나로 통일해야겠어요

2022-03-26 08:48 UTC, merged