ui-testing-handbook 의 7장 automate 초벌 번역
Korean-Translation-2022/learnstorybook.com pull request #2
Opened 2022-02-05 12:42 UTC by twinstae

-다 체로 번역했어요.
- 여러 영어 용어들을 어떻게 할지, 용어집 만들면서 결정해보기로 했었지요. 지금은 일단 번역해본 것도 있지만. 저희 합의했던 대로 영어로 대부분 그대로 남기는 방향으로 고치려 해요.
  - 시각visual과 구성 composition 테스트
  - 컴포넌트, UI 테스팅

2022-02-05 13:08 UTC, MiryangJung requested changes

2022-02-05 13:08 UTC, MiryangJung commented on content/ui-testing-handbook/react/ko/automate.md
> +Pull request (PR)이 production 코드를 망가트리지 않는다는 걸 보장하기 위해서, 여러분은 보통 코드를 pull 해와서 테스트 suite를 로컬에서 실행해볼 것이다. 이런 작업은 workflow 흐름을 끊고 시간도 오래 걸린다. 지속적 통합(CI)을 통해서, 손으로 하나하나 개입하지 않고도 테스트의 이득은 모두 챙길 수 있다.
저는 workflow를 **작업 흐름** 으로 번역했는데 이 부분은 논의가 필요하겠네요!

2022-02-05 13:08 UTC, MiryangJung commented on content/ui-testing-handbook/react/ko/automate.md
> +여러분은 UI를 바꿀 수도, 새로운 기능을 만들 수도, 의존성을 최신화할 수도 있다. Pull request를 열었을 때, CI 서버는 자동적으로 포괄적인 UI테스트-시각, 구성, 접근성, 상호작용, 유저 흐름(user flows)-를 실행해준다.
**유저 흐름(user flows)-** 이렇게 보이는데 **-** 가 오타인 듯합니다.

2022-02-05 13:08 UTC, MiryangJung commented on content/ui-testing-handbook/react/ko/automate.md
> +테스트 결과를 PR뱃지들로 받게 되고, 이를 통해 모든 검사 결과를 개략적으로 확인할 수 있다.
**개략적** 오타일까요?

2022-02-05 13:08 UTC, MiryangJung commented on content/ui-testing-handbook/react/ko/automate.md
> +한눈에 봐도, pull request가 모든 품질 검사를 통과했는지 말할 수 있다. 그 답이 "네(yes)"라면 실제 코드를 리뷰하는 단계로 넘아가면 된다. 그렇지 못한 경우에는, 로그를 살펴보면서 무엇이 잘못됐는지 찾는다.
넘아가면 > 넘어가면으로 수정해야 될 듯합니다.

2022-02-05 13:08 UTC, MiryangJung commented on content/ui-testing-handbook/react/ko/automate.md
> +우리가 만든 testing workflow는 Storybook을 이용해 독립된 컴포넌트로 시작한다. 코드를 짜는 동안 검사를 실행하면서 더 빠른 피드백 고리(feedback loop)를 만들 수 있다. 마지막으로 여러분의 모든 테스트 suite를 continuous integration을 이용해서 실행해보도록 하자.
continuous integration 를 한국어로 표현할 수 없을까요? 저는 읽으면서 이 단어가 무슨 의미인지 잘 모르겠어요.

2022-02-05 13:28 UTC, twinstae commented on content/ui-testing-handbook/react/ko/automate.md
> +Pull request (PR)이 production 코드를 망가트리지 않는다는 걸 보장하기 위해서, 여러분은 보통 코드를 pull 해와서 테스트 suite를 로컬에서 실행해볼 것이다. 이런 작업은 workflow 흐름을 끊고 시간도 오래 걸린다. 지속적 통합(CI)을 통해서, 손으로 하나하나 개입하지 않고도 테스트의 이득은 모두 챙길 수 있다.
job이나 workflow는 둘 다 작업, 작업 흐름으로 번역해볼까 했는데, 일단 대부분 영어 그대로 나뒀어요. job이랑 workflow는 아예 의미가 달라서 작업/작업 흐름보다 더 구분해야 할 것도 같고. "잡"이라 음차하기도 좀 그렇네요. CI 에서만 쓰이는 용어라, 다른 장에서도 쓰일 것 같진 않은데요.

자세한 건 회의에서 논의해보면 좋겠어요. 제가 안건 목록을 만들어볼게요.

2022-02-05 13:29 UTC, twinstae commented on content/ui-testing-handbook/react/ko/automate.md
> +여러분은 UI를 바꿀 수도, 새로운 기능을 만들 수도, 의존성을 최신화할 수도 있다. Pull request를 열었을 때, CI 서버는 자동적으로 포괄적인 UI테스트-시각, 구성, 접근성, 상호작용, 유저 흐름(user flows)-를 실행해준다.
아하. 오타는 아니고 시각 앞에서부터 시작해서 -부연설명- 이 있는 구조에요. 

> -시각, 구성, 접근성, 상호작용, 유저 흐름(user flows)-

2022-02-05 13:33 UTC, twinstae commented on content/ui-testing-handbook/react/ko/automate.md
> +테스트 결과를 PR뱃지들로 받게 되고, 이를 통해 모든 검사 결과를 개략적으로 확인할 수 있다.
"You’ll get test results via PR badges, which provide a summary of all the checks"를 의역해봤어요. 개략적은 "대충 추려 간략하게 개괄한"이라는 뜻이라 summary랑 비슷하게 느껴졌거든요.

직역하면 이런 느낌이에요. "모든 체크들을 요약해주는 PR badge로 테스트 결과를 받게 된다."
직역도 나쁘진 않은데, 저는 영어 어순을 그대로 유지하고 싶었어요. 지금 보니 직역이 더 좋게 느껴지는군요.

2022-02-05 13:36 UTC, twinstae commented on content/ui-testing-handbook/react/ko/automate.md
> +한눈에 봐도, pull request가 모든 품질 검사를 통과했는지 말할 수 있다. 그 답이 "네(yes)"라면 실제 코드를 리뷰하는 단계로 넘아가면 된다. 그렇지 못한 경우에는, 로그를 살펴보면서 무엇이 잘못됐는지 찾는다.
오타는 수정했어요!

2022-02-05 13:36 UTC, twinstae commented on content/ui-testing-handbook/react/ko/automate.md
> +우리가 만든 testing workflow는 Storybook을 이용해 독립된 컴포넌트로 시작한다. 코드를 짜는 동안 검사를 실행하면서 더 빠른 피드백 고리(feedback loop)를 만들 수 있다. 마지막으로 여러분의 모든 테스트 suite를 continuous integration을 이용해서 실행해보도록 하자.
지속적 통합(Continuous Integration)으로 병기했어요.

2022-02-06 10:35 UTC, lisohh commented on content/ui-testing-handbook/react/ko/automate.md
> +Pull request (PR)이 production 코드를 망가트리지 않는다는 걸 보장하기 위해서, 여러분은 보통 코드를 pull 해와서 테스트 suite를 로컬에서 실행해볼 것이다. 이런 작업은 workflow 흐름을 끊고 시간도 오래 걸린다. 지속적 통합(CI)을 통해서, 손으로 하나하나 개입하지 않고도 테스트의 이득은 모두 챙길 수 있다.
저는 그대로 workflow라고 썼는데 오늘 의논해요!

2022-02-13 12:11 UTC, perfumelim requested changes

2022-03-13 10:47 UTC, lisohh requested changes
수정 요청합니다~

2022-03-13 10:47 UTC, lisohh commented on content/ui-testing-handbook/react/ko/automate.md
> +이런 workflow를 자동화해서 개발자가 code를 push할 때마다 테스트가 작동하게 만들 수 있습니다. 테스트들은 background에서 실행되고 완료되면 결과를 보고합니다. 이는 회귀(regressions) 에러를 자동으로 감지할 수 있게 해줍니다.
workflow -> 작업 흐름(workflow)도 같이 얘기해봐야겠네요 오느을

2022-03-13 10:47 UTC, lisohh commented on content/ui-testing-handbook/react/ko/automate.md
> +코드 리뷰는 개발자가 되는데 중요한 부분입니다. 버그를 조기에 발견하고 높은 코드 품질을 유지할 수 있게 돕습니다.
되는 데 로 바꿔주세요

2022-03-13 10:47 UTC, lisohh commented on content/ui-testing-handbook/react/ko/automate.md
> +코드 리뷰는 개발자가 되는데 중요한 부분입니다. 버그를 조기에 발견하고 높은 코드 품질을 유지할 수 있게 돕습니다.
뒤에 문장에 주어가 없으니 간단하긴 하지만 약간 어색하네요. 주어를 넣으면 어떨까요

2022-03-13 10:47 UTC, lisohh commented on content/ui-testing-handbook/react/ko/automate.md
> +Pull request (PR)이 production 코드를 망가트리지 않는다는 걸 보장하기 위해서, 여러분은 보통 코드를 pull 해와서 테스트 suite를 로컬에서 실행해볼 겁니다. 이런 작업은 workflow 흐름을 끊고 시간도 오래 걸립니다. 지속적 통합(CI)을 통해서, 손으로 하나하나 개입하지 않고도 테스트의 이득은 모두 챙길 수 있습니다.
여기서 보장이 ensure의 번역으로 쓰였는데 다른 글에서는 확인으로 쓰인데도 있는 것 같아요.. 이것도 다같이 맞춰야 하겠어요

2022-03-13 10:47 UTC, lisohh commented on content/ui-testing-handbook/react/ko/automate.md
> +여러분은 UI를 바꿀 수도, 새로운 기능을 만들 수도, 의존성을 최신화할 수도 있다. Pull request를 열었을 때, CI 서버는 자동적으로 포괄적인 UI테스트-시각, 구성, 접근성, 상호작용, 유저 흐름(user flows)-를 실행해줍니다.
update를 그냥 업데이트로 쓰자고 단어 스프레드 시트에 쓰여있네요 일단은?

2022-03-13 10:47 UTC, lisohh commented on content/ui-testing-handbook/react/ko/automate.md
> +여러분은 UI를 바꿀 수도, 새로운 기능을 만들 수도, 의존성을 최신화할 수도 있다. Pull request를 열었을 때, CI 서버는 자동적으로 포괄적인 UI테스트-시각, 구성, 접근성, 상호작용, 유저 흐름(user flows)-를 실행해줍니다.
interaction도 상호작용이 아닌 인터랙션으로 바꿔주세요

2022-03-13 10:47 UTC, lisohh commented on content/ui-testing-handbook/react/ko/automate.md
> +테스트 결과를 PR뱃지들로 받게 되고, 이를 통해 모든 검사 결과를 개략적으로 확인할 수 있습니다.
테스트 결과로 PR뱃지들을 받게 되고~ 가 더 매끄러울 것 같습니닷

2022-03-13 10:47 UTC, lisohh commented on content/ui-testing-handbook/react/ko/automate.md
> +지난 다섯 챕터들에서는 Taskbox UI의 다양한 면을 어떻게 테스트할 수 있는지 보여주었습니다. 여기에 더해서 우리는 이제 지속적 통합(CI)을 Github Actions를 이용해 구축해볼 것입니다.
더불어 우리는 이제 Github Actions를 이용해 지속적 통합(CI)을  구축해볼 것입니다. 가 더 매끄러울 것 같아요

2022-03-13 10:47 UTC, lisohh commented on content/ui-testing-handbook/react/ko/automate.md
> +우리가 만들 workflow는 코드가 repository의 어떤 branch에라도 push되는 순간 실행되고, 3가지 작업(job)이 있습니다.
코드가 repository의 어떤 branch에라도 push되는 순간 실행되고, 이 문장이 죄금 어색하네요;

2022-03-13 10:47 UTC, lisohh commented on content/ui-testing-handbook/react/ko/automate.md
> +Chapter 8 에서 이 완전한 작업 흐름을 실제로 보여주겠습니다. 새 기능을 production에 올리기 전에 어떻게 테스트할 수 있는지 보겠습니다.
Chapter 8 illustrates this complete workflow in action. We'll see how to test a new feature before shipping it to prod.
번역이 살짝 딱딱해서 아래처럼 바꾸면 어떨까요?
 'Chapter 8은 이러한 완전한 작업 흐름(workflow)을 실제로 보여줍니다. 이제 새 기능을 ~'

2022-03-13 10:49 UTC, lisohh commented on content/ui-testing-handbook/react/ko/workflow.md
> +이 할일 컴포넌트는 이미 사용자가 할일을 수정할 수 있고, pin해둘 수 있고, 보관할 수 있습니다. 이제 삭제 버튼을 추가하고, 이 버튼을 application 상태에 연결해서 삭제 기능을 추가해보겠습니다.
그렇네요

2022-03-13 11:05 UTC, lisohh requested changes
수정 요청 드립니다~

2022-03-13 11:05 UTC, lisohh commented on content/ui-testing-handbook/react/ko/workflow.md
> +`yarn test`를 실행해서 모든 테스트가 통과하는지 확인합니다. Jest가 watch 모드에서 어떻게 작동하는지 주의를 기울여보면, 변경된 파일과 관련된 테스트만 실행한다는 걸 알 수 있습니다.
Notice how Jest runs in watch mode and only executes tests related to files that changed.를 
'Jest가 어떻게 watch 모드에서 실행되며 변경된 파일과 관련된 테스트만 실행하는지 살펴보세요.'로 번역하는 것이 더 적절할 것 같아요.

2022-03-13 11:05 UTC, lisohh commented on content/ui-testing-handbook/react/ko/workflow.md
> +## 사용자 흐름 테스트
사용자 흐름도 다른 흐름들에 맞춰 영어를 병기할까요? 얘기해봅시다

2022-03-13 11:05 UTC, lisohh commented on content/ui-testing-handbook/react/ko/workflow.md
> +다른 모든 테스트처럼, Github actions는 E2E테스트도 Cypress를 이용해서 실행할 겁니다.
Github actions는 E2E테스트도 Cypress를 이용해서 실행할 겁니다. 
이 문장이 약간 어색합니다.

2022-03-13 11:05 UTC, lisohh commented on content/ui-testing-handbook/react/ko/workflow.md
> +## 모험의 시작
일부러 다른 것들에 맞춰서 단어 형태로 번역한 것 같은데 문장 형식이 더 좋을 것 같아요 보는 사람의 입장에서?

2022-03-13 11:05 UTC, lisohh commented on content/ui-testing-handbook/react/ko/workflow.md
> +**UI 테스팅 핸드북**은 프로 프런트 엔드 팀이 사용하는 테스트 전략을 강조합니다. 이 테스트들은 앱의 health checks처럼 돌아가고, 시각적인 외관(viusal appearance)부터 UI 로직을 검증할 뿐만 아니라, 심지어 통합 이슈까지 감지합니다. 게다가, 지속적 통합으로 매 커밋을 자동으로 테스트하면 버그를 감소시킬 수 있습니다.
시각적인 외관 말고 다르게 바꾸는게 어떨까요?

2022-03-25 11:47 UTC, lisohh commented on content/ui-testing-handbook/react/ko/automate.md
> +이런 workflow를 자동화해서 개발자가 code를 push할 때마다 테스트가 작동하게 만들 수 있습니다. 테스트들은 background에서 실행되고 완료되면 결과를 보고합니다. 이는 회귀(regressions) 에러를 자동으로 감지할 수 있게 해줍니다.
이거 작업흐름(workflow)으로 고쳐주세용

2022-03-25 12:29 UTC, twinstae commented on content/ui-testing-handbook/react/ko/automate.md
> +description: '작업 흐름(workflow)를 더 빠르게 만들고, 더 고품질의 코드를 전달하기'
정정했습니다.

2022-03-25 12:30 UTC, twinstae commented on content/ui-testing-handbook/react/ko/automate.md
> +개발자는 평균적으로 버그를 고치는데 [매주 4-8 시간 정도](https://www.niss.org/sites/default/files/technicalreports/tr81.pdf)를 사용한다고 합니다. 버그가 production에 몰래 끼어들기 시작하면, 상황은 나빠지기만 합니다. 버그를 고치는데에는 [5-10x](https://www.cs.umd.e
5-10배 로 바꿨습니다.

2022-03-25 12:33 UTC, twinstae commented on content/ui-testing-handbook/react/ko/automate.md
> +여러분은 UI를 바꿀 수도, 새로운 기능을 만들 수도, 의존성을 최신화할 수도 있다. Pull request를 열었을 때, CI 서버는 자동적으로 포괄적인 UI테스트-시각, 구성, 접근성, 상호작용, 유저 흐름(user flows)-를 실행해줍니다.
-시각부터 시작해서 -끝나는 건데. 더 잘 보이게 수정할게요.

2022-03-25 12:36 UTC, twinstae commented on content/ui-testing-handbook/react/ko/automate.md
> +한눈에 봐도, pull request가 모든 품질 검사를 통과했는지 말할 수 있습니다. 그 답이 "네(yes)"라면 실제 코드를 리뷰하는 단계로 넘어가면 됩니다. 그렇지 못한 경우에는, 로그를 살펴보면서 무엇이 잘못됐는지 찾습니다.
"pull request가 모든 품질 검사를 통과했는지 한눈에 알 수 있습니다."로 바꿨어요!

2022-03-25 12:36 UTC, twinstae commented on content/ui-testing-handbook/react/ko/workflow.md
> +title: 'UI Testing Playbook'
번역했어요.

2022-03-25 12:36 UTC, twinstae commented on content/ui-testing-handbook/react/ko/automate.md
> +Pull request (PR)이 production 코드를 망가트리지 않는다는 걸 보장하기 위해서, 여러분은 보통 코드를 pull 해와서 테스트 suite를 로컬에서 실행해볼 겁니다. 이런 작업은 workflow 흐름을 끊고 시간도 오래 걸립니다. 지속적 통합(CI)을 통해서, 손으로 하나하나 개입하지 않고도 테스트의 이득은 모두 챙길 수 있습니다.
용어 통일하면서 일괄 수정하죠!

2022-03-25 12:38 UTC, twinstae commented on content/ui-testing-handbook/react/ko/workflow.md
> +UI의 서로 다른 부분을 테스트 하는 도구를 찾기는 쉽습니다. 하지만 이 모든 걸 생산적인 워크 플로우로 어떻게 결합하는 노하우는 까다롭습니다. 잘못 이해하면, 유지보수 악몽으로 빨려들어갈 수도 있습니다.
일단 통일해둘게요!

2022-03-25 12:38 UTC, twinstae commented on content/ui-testing-handbook/react/ko/workflow.md
> +이 할일 컴포넌트는 이미 사용자가 할일을 수정할 수 있고, pin해둘 수 있고, 보관할 수 있습니다. 이제 삭제 버튼을 추가하고, 이 버튼을 application 상태에 연결해서 삭제 기능을 추가해보겠습니다.
이것도 검수에서 용어 통일하면서 이야기해봐요.

2022-03-25 12:43 UTC, twinstae commented on content/ui-testing-handbook/react/ko/workflow.md
> +Task UI를 약간 고쳤을 때, 이를 사용하는 다른 컴포넌트를 의도치 않게 변경해버릴 수도 있습니다. TaskList나 InboxScreen처럼요. Chromatic으로 visual 테스트를 실행하면 이를 잡아낼 겁니다. 이를 통해 모든 게 정확하게 연결되어 있다는 걸 보장해주기도 합니다.
일단 시각적 테스트로 해뒀어요. 통일해야 하는 용어들을 잘 정리를 해두겠습니다.

2022-03-25 12:43 UTC, twinstae commented on content/ui-testing-handbook/react/ko/workflow.md
> +개발 중에는, InboxScreen stories를 이용해서 직접(manually) interaction을 검증합니다. 기대한대로 동작한다면, Jest나 Testing Library로 상호작용 테스트를 추가하는 단계로 넘어갈 수 있습니다.
네. 최종에서는 하나로 통일하고 괄호를 없애죠

2022-03-25 12:45 UTC, twinstae commented on content/ui-testing-handbook/react/ko/automate.md
> +여러분은 UI를 바꿀 수도, 새로운 기능을 만들 수도, 의존성을 최신화할 수도 있다. Pull request를 열었을 때, CI 서버는 자동적으로 포괄적인 UI테스트-시각, 구성, 접근성, 상호작용, 유저 흐름(user flows)-를 실행해준다.
그렇게 했어요.

2022-03-25 12:49 UTC, twinstae commented on content/ui-testing-handbook/react/ko/automate.md
> +지난 다섯 챕터들에서는 Taskbox UI의 다양한 면을 어떻게 테스트할 수 있는지 보여주었습니다. 여기에 더해서 우리는 이제 지속적 통합(CI)을 Github Actions를 이용해 구축해볼 것입니다.
반영했어요!

2022-03-25 12:51 UTC, twinstae commented on content/ui-testing-handbook/react/ko/automate.md
> +Chapter 8 에서 이 완전한 작업 흐름을 실제로 보여주겠습니다. 새 기능을 production에 올리기 전에 어떻게 테스트할 수 있는지 보겠습니다.
반영했어요

2022-03-25 12:53 UTC, twinstae commented on content/ui-testing-handbook/react/ko/workflow.md
> +### 접근성 검사
일단 테스트로 해놨습니다.

2022-03-25 12:54 UTC, twinstae commented on content/ui-testing-handbook/react/ko/workflow.md
> +회귀 오류를 잡아내기 위해서 모든 컴포넌트를 검사해야 합니다. stories를 test file에 모두 import하고 에 [jest-axe](https://github.com/twilio-labs/paste/blob/cd0ddad508e41cb9982a693a5160f1b7866f4e2a/packages/paste-core/components/check
반영

2022-03-25 12:55 UTC, twinstae commented on content/ui-testing-handbook/react/ko/workflow.md
> +`yarn test`를 실행해서 모든 테스트가 통과하는지 확인합니다. Jest가 watch 모드에서 어떻게 작동하는지 주의를 기울여보면, 변경된 파일과 관련된 테스트만 실행한다는 걸 알 수 있습니다.
반영!

2022-03-25 12:57 UTC, twinstae commented on content/ui-testing-handbook/react/ko/workflow.md
> +다른 모든 테스트처럼, Github actions는 E2E테스트도 Cypress를 이용해서 실행할 겁니다.
어순을 바꿔봤어요.

2022-03-25 12:59 UTC, twinstae commented on content/ui-testing-handbook/react/ko/workflow.md
> +**UI 테스팅 핸드북**은 프로 프런트 엔드 팀이 사용하는 테스트 전략을 강조합니다. 이 테스트들은 앱의 health checks처럼 돌아가고, 시각적인 외관(viusal appearance)부터 UI 로직을 검증할 뿐만 아니라, 심지어 통합 이슈까지 감지합니다. 게다가, 지속적 통합으로 매 커밋을 자동으로 테스트하면 버그를 감소시킬 수 있습니다.
겉모습이라고 해봤어요. 이것도 통일을 해보죠.

2022-03-25 13:00 UTC, merged