Intro to Storybook 1장 Get Started 초벌 번역
Korean-Translation-2022/learnstorybook.com pull request #6
Opened 2022-02-06 03:37 UTC by vanillovin

번역했어용

2022-02-06 11:14 UTC, MiryangJung requested changes

2022-02-06 11:14 UTC, MiryangJung commented on content/intro-to-storybook/react/ko/get-started.md
>  우리는 다양한 환경에서 애플리케이션이 올바르게 작동하는지 다음 명령어를 통해 빠르게 확인할 수 있습니다:
지워야 되는 문장인 듯해요~

2022-02-06 12:02 UTC, vanillovin commented on content/intro-to-storybook/react/ko/get-started.md
>  우리는 다양한 환경에서 애플리케이션이 올바르게 작동하는지 다음 명령어를 통해 빠르게 확인할 수 있습니다:
지웠씁니다!

2022-02-11 08:07 UTC, cottonpup requested changes
니다,세요 체로 변경해주세요!

2022-02-11 15:59 UTC, MiryangJung requested changes

2022-02-11 15:59 UTC, MiryangJung commented on content/intro-to-storybook/react/ko/get-started.md
> +이 단계에서는 파일을 로컬 저장소(repository)에 추가하는 것이 안전합니다. 다음 명령을 실행하여 로컬 저장소를 초기화하고 지금까지 수행하 변경 사항(내용)을 추가 및 커밋하세요.
수행하 변경  > 이 부분 뭔가 글자 하나가 씹힌 듯합니다!

2022-02-11 15:59 UTC, MiryangJung commented on content/intro-to-storybook/react/ko/simple-component.md
> +스토리를 정의하기 위해, 각각의 테스트 state에 해당하는 스토리를 만들기 위해서 우리는 함수를 내보냅니다. 스토리는 주어진 state 안에서 렌더링 된 요소(즉, prop이 포함된 컴포넌트)를 return(반환) 하는 함수입니다. 정확히는(이는?) [함수형 컴포넌트(Functional Component)](https://reactjs.org/docs/
정확히는(이는?)  > 일부러 이렇게 적으신 건가요??

2022-02-11 15:59 UTC, MiryangJung commented on content/intro-to-storybook/react/ko/simple-component.md
> +[`매개변수(parameters)`](https://storybook.js.org/docs/react/writing-stories/parameters)는 일반적으로 Storybook의 기능과 추가 기능(addons)의 동작을 제어하기 위하여 사용됩니다. 우리의 경우에는 이를 사용하여 `actions`(mocked callbacks)이 처리되는 방식을 구성
addons는 *애드온* 으로 표기합니다.

2022-02-13 12:12 UTC, vanillovin commented on content/intro-to-storybook/react/ko/simple-component.md
> +스토리를 정의하기 위해, 각각의 테스트 state에 해당하는 스토리를 만들기 위해서 우리는 함수를 내보냅니다. 스토리는 주어진 state 안에서 렌더링 된 요소(즉, prop이 포함된 컴포넌트)를 return(반환) 하는 함수입니다. 정확히는(이는?) [함수형 컴포넌트(Functional Component)](https://reactjs.org/docs/
앗 모르겠네유! 수정하겠습니다 ㅎ

2022-02-13 12:13 UTC, vanillovin commented on content/intro-to-storybook/react/ko/simple-component.md
> +[`매개변수(parameters)`](https://storybook.js.org/docs/react/writing-stories/parameters)는 일반적으로 Storybook의 기능과 추가 기능(addons)의 동작을 제어하기 위하여 사용됩니다. 우리의 경우에는 이를 사용하여 `actions`(mocked callbacks)이 처리되는 방식을 구성
넵!! 근데 미량님 밑에 Resolve conversation 이거랑 Squash and merge 이건 무슨 버튼이죵? 누르면 안 되겠죠??

2022-02-20 11:50 UTC, MiryangJung commented on content/intro-to-storybook/react/ko/simple-component.md
> +[`매개변수(parameters)`](https://storybook.js.org/docs/react/writing-stories/parameters)는 일반적으로 Storybook의 기능과 추가 기능(addons)의 동작을 제어하기 위하여 사용됩니다. 우리의 경우에는 이를 사용하여 `actions`(mocked callbacks)이 처리되는 방식을 구성
머지 누르면 이거 닫히고 머지되어요! 리뷰어 2명 approve받으면 눌러주세요.

2022-02-20 11:50 UTC, MiryangJung approved these changes

2022-03-13 12:19 UTC, lisohh requested changes

2022-03-13 12:19 UTC, lisohh commented on content/intro-to-storybook/react/ko/simple-component.md
>  `Task` 컴포넌트를 만들기 시작할 때 먼저 위에서 살펴본 여러 유형의 task에 해당하는 테스트 상태(satate)를 작성합니다. 그런 다음 모의(mocked) 데이터를 사용하여 독립적 환경에서 컴포넌트를 구축하기 위해 Storybook을 사용합니다. 각각의 state에 따라 컴포넌트의 모습을 수동으로 테스트합니다.
state 오타났어요~

2022-03-13 12:20 UTC, lisohh approved these changes

2022-03-13 12:22 UTC, pak-fuse commented on content/intro-to-storybook/react/ko/composite-component.md
> +💡 <a href="https://storybook.js.org/docs/react/writing-stories/decorators"><b>데코레이터(Decorators)</b></a>는 스토리에 임의의 래퍼(wrapper)를 제공하는 한 방법입니다. 위의 예시에서 우리는 데코레이터 `key`를 사용하여 기본 내보내기에서 렌더링 된 컴포넌트에 `paddi
감싸 줄 때 -> 감싸줄 때

2022-03-13 12:23 UTC, pak-fuse reviewed
밍지님 수고하셨어요 😉

2022-03-13 12:26 UTC, pak-fuse commented on content/intro-to-storybook/react/ko/simple-component.md
>  `Task` 컴포넌트를 만들기 시작할 때 먼저 위에서 살펴본 여러 유형의 task에 해당하는 테스트 상태(satate)를 작성합니다. 그런 다음 모의(mocked) 데이터를 사용하여 독립적 환경에서 컴포넌트를 구축하기 위해 Storybook을 사용합니다. 각각의 state에 따라 컴포넌트의 모습을 수동으로 테스트합니다.
mocked을 '모의'라고 하는 게 좋을까요?

2022-03-15 09:46 UTC, closed without merging