디자인 시스템 소개 - 1장 introduction
Korean-Translation-2022/learnstorybook.com pull request #8
Opened 2022-02-06 10:08 UTC by penguin311

디자인 시스템 소개 - 1장 introduction 번역완료

2022-02-06 11:21 UTC, MiryangJung requested changes

2022-02-06 11:21 UTC, MiryangJung commented on content/design-systems-for-developers/react/ko/introduction.md
> +<div class="aside">이 가이드는 <b>전문 개발자들을 위한</b> 디자인 시스템 학습법에 대 다루고있다. 자바스크립트(JavaScript), 깃(Git), 그리고 지속적인 통합 환경(Continuous Integration, CI)에 대해 어느 정도 경험을 하고 읽기를 권한다. 또한 스토리 작성이나 설정 파일 수정 등의 스토리북의 기본 사용
시스템 학습법에 대 다루고있다 > 시스템 학습법에 대해 다루고있다.
오타인 듯합니다.

있어야한다. > 있어야 한다. 맞춤법

2022-02-06 11:21 UTC, MiryangJung commented on content/design-systems-for-developers/react/ko/introduction.md
> +개발자의 경우, 몇 가지는 필수적으로, 프로덕션 디자인 시스템에는 UI 컴포넌트와 프론트엔드 인프라구조를 포함해야 한다. 디자인 시스템을 위한 3가지 기술적가 있는데, 그것이 우리가 이 가이드에서 다룰 내용이다.
디자인 시스템을 위한 3가지 기술적가 있는데 
문장이 어색합니다.

2022-02-06 11:21 UTC, MiryangJung commented on content/design-systems-for-developers/react/ko/introduction.md
> +이런 유명세에도 불구하고, 디자인 시스템이 모든 문제를 해결해주지는 않는다. 만약 소규모의 팀에서 단일 앱으로 작업하는 경우, 디자인 시스템을 사용하도록 인프라를 설정하는 대신 UI 컴포넌트로 이루어진 디렉터리를 사용하는 것이 좋다. 작은 프로젝트의 경우 유지보수 비용, 환경 통합, 도구에 드는 비용이 생산성 향상에 드는 비용보다 훨씬 커질것이다.
커질것이다. > 커질 것이다.

2022-02-06 11:21 UTC, MiryangJung commented on content/design-systems-for-developers/react/ko/introduction.md
> +#### UI 컴포넌트는 격리시켜 작업하기
격리시킨다는 단어가 어색한 거 같아서 논의필요한 듯합니다!

2022-02-06 11:21 UTC, MiryangJung commented on content/design-systems-for-developers/react/ko/introduction.md
> +모든 디자인 시스템은 UI 컴포넌트들로 구성된다. 우리는 스토리북을 "워크벤치(workbench)"로 사용하여 소비자 앱 밖에서 UI 컴포넌트를 구축할것이다. 그다음엔 스토리북에서 컴포넌트의 내구성을 향상시키는 애드온들(Actions, Source, Knobs)을 통합할 것이다.
구축할것이다 > 구축할 것이다

2022-02-06 11:21 UTC, MiryangJung commented on content/design-systems-for-developers/react/ko/introduction.md
> +개발자에게 문서 작업은 필수적이지만, 이를 생성하는 건 개발자의 우선순위 작업은 아니다. 스토리북에서는 최소한의 설정을 통해 문서를 자동으로 생성할 수 있어, UI 컴포넌트를 문서화할수있다.
문서화할수있다. > 문서화할 수 있다.

2022-02-06 11:49 UTC, pak-fuse commented on content/design-systems-for-developers/react/ko/introduction.md
> +선도적인 디자인 시스템 팀들은 어떤이유로 그 기술과 도구를 사용할까? 공동 저자 톰과 함께 스토리북 커뮤니티의 우수 사례들을 통해 성공적인 디자인 시스템의 특성을 연구했다.
어떤이유로 -> 어떤 이유로

2022-02-06 11:49 UTC, pak-fuse commented on content/design-systems-for-developers/react/ko/introduction.md
> +디자이너들은 종종 도구 안에서 디자인 시스템을 구축하는 것에 대해 이야기한다. 디자인 시스템의 전체적 범위는 자산(Sketch, Figma 등), 설계 원리, 기여 구조, 거버넌스와 그 이상을 포괄한다. 디자이너 중심의 가이드는 이미 많기에, 여기서는 자세히 다루지 않겠다.
거버넌스가 뭔지 모르겠어요...

2022-02-06 12:17 UTC, pak-fuse commented on content/design-systems-for-developers/react/ko/introduction.md
> +이 파트들은 패키지 관리자를 통해 패키지화, 버전화되어 앱으로 배포된다.
파트로 할 것인지, 챕터로 할 것인지

2022-02-11 13:57 UTC, penguin311 commented
리뷰 resolve 하였습니다!

2022-02-12 10:50 UTC, pak-fuse commented on content/design-systems-for-developers/react/ko/introduction.md
> +<div class="aside">이 가이드는 <b>전문 개발자들을 위한</b> 디자인 시스템 학습법에 대해 다루고있습니다. 자바스크립트(JavaScript), 깃(Git), 그리고 지속적인 통합 환경(Continuous Integration, CI)에 대해 어느 정도 경험을 하고 읽기를 권합니다. 또한 스토리 작성이나 설정 파일 수정 등의 스토리북의 기
다루고있습니다. -> 다루고 있습니다.

2022-02-12 10:50 UTC, pak-fuse commented on content/design-systems-for-developers/react/ko/introduction.md
> +선도적인 디자인 시스템 팀들은 어떤 이유로 그 기술과 도구를 사용할까요? 공동 저자 톰과 함께 스토리북 커뮤니티의 우수 사례들을 통해 성공적인 디자인 시스템의 특성을 연구했습니다.
스토리북 -> Storybook

2022-02-12 10:50 UTC, pak-fuse commented on content/design-systems-for-developers/react/ko/introduction.md
> +이 단계별 가이드에서는 확장된 프로덕션 디자인 시스템에 사용되는 자동화된 툴과 신중한 워크플로우에 대해 설명한다. 우리는 기존 컴포넌트 라이브러리를 조합하여 디자인 시스템이 만들어지는 과정을 살펴본 후, 핵심 서비스와 라이브러리, 워크플로우에 대해 알아볼 것입니다.
설명한다. -> 설명합니다.

2022-02-12 10:50 UTC, pak-fuse commented on content/design-systems-for-developers/react/ko/introduction.md
>  - ⚛️ [리액트(React)](https://reactjs.org/): 선언 중심 컴포넌트 UI(create-react-app)를 사용한다.
사용한다. -> 사용합니다.

2022-02-12 10:50 UTC, pak-fuse commented on content/design-systems-for-developers/react/ko/introduction.md
>  - ✅ [Chromatic](https://chromatic.com): 컴포넌트에서 일어나는 오류를 시각적으로 발견할 수 있습니다(스토리북 메인테이너들이 제작했다).
제작했다. -> 제작했습니다.

2022-02-12 10:50 UTC, pak-fuse commented on content/design-systems-for-developers/react/ko/introduction.md
> +다음 장에서는 서로 다른 컴포넌트 라이브러리에서 디자인 시스템을 추출하는 방법에 대해 알아볼 것입니다.
'스토리북'으로 되어있는 것 Storybook으로 수정해주세요!

2022-02-12 10:54 UTC, pak-fuse commented on content/design-systems-for-developers/react/ko/architecture.md
> +우리도 이러한 곤경에 빠졌습니다. 팀이 숙련되었음에도 불구하고, UI 컴포넌트는 끊임없이 불어나고 재구성되었습니다. UI 패턴의 모양과 기능이 동일할것을 기대했지만, 각각의 컴포넌트는 진실의 근원(source of truth)을 분별할 수 없을 정도로 독특한 모양을 띠었습니다. 기여도 또한 현저히 낮았습니다.
동일할것 -> 동일할 것

2022-02-12 10:54 UTC, pak-fuse commented on content/design-systems-for-developers/react/ko/architecture.md
>  개발자에게 유용한 휴리스틱:
:(콜론)을 -(대쉬)로 변경해주세요.

2022-02-12 10:54 UTC, pak-fuse commented on content/design-systems-for-developers/react/ko/architecture.md
>  개발자에게 유용한 휴리스틱:
여기서 혹시 휴리스틱이 뭐라고 설명이 있었나요...?

2022-03-01 08:02 UTC, pak-fuse reviewed
영어로만 되어 있는 주석 부분은 번역 안하는 걸까요...?

2022-03-01 08:02 UTC, pak-fuse commented on content/design-systems-for-developers/react/ko/introduction.md
> +- ✅ [Chromatic](https://chromatic.com): 컴포넌트에서 일어나는 오류를 시각적으로 발견할 수 있습니다(Storybook 메인테이너들이 제작함).
제작함 -> 제작 은 어떨까요

2022-03-13 12:28 UTC, merged