Lisoh
Korean-Translation-2022/learnstorybook.com pull request #9
Opened 2022-02-06 10:30 UTC by lisohh

Part3의 Interaction-testing.md파일을 초벌 번역했습니다.

2022-02-06 11:27 UTC, MiryangJung requested changes

2022-02-06 11:27 UTC, MiryangJung commented on content/ui-testing-handbook/react/ko-kr/interaction-testing.md
> +이 장에서는 독자들에게 컴퓨터를 사용하여 사용자 상호 작용을 시뮬레이션하고 확인하는 방법에 대해 일러준다.
일러준다. 단어가 어색한 느낌이에요.

2022-02-06 11:27 UTC, MiryangJung commented on content/ui-testing-handbook/react/ko-kr/interaction-testing.md
> +상태가 올바르게 업데이트 되었는지 확인한다.
한 줄로 입력되어야 할 듯합니다.

2022-02-06 11:27 UTC, MiryangJung commented on content/ui-testing-handbook/react/ko-kr/interaction-testing.md
> +해보자. `InboxScreen.test.js`파일을 만들고 첫 번째 테스트를 작성해라.위의 예와 같이 우리는 이러한 테스트에 스토리를 가져와서 Testing-Library에 잇는 'render'기능을 이용해 쌓는다.
작성해라.위의 > 작성해라. 위의

2022-02-06 11:27 UTC, MiryangJung commented on content/ui-testing-handbook/react/ko-kr/interaction-testing.md
> +우리는 Testing Library을 이용해 스토리를 올리고 렌더링하는 테스트를 성공적으로 작성했다.그 후 시뮬레이션된 유저 동작을 적용하고 해당 컴포넌트의 상태가 정확히 업데이트 되었는지 확인한다.
작성했다.그 후 > 작성했다. 그 후

2022-02-06 11:41 UTC, lisohh commented on content/ui-testing-handbook/react/ko-kr/interaction-testing.md
> +이 장에서는 독자들에게 컴퓨터를 사용하여 사용자 상호 작용을 시뮬레이션하고 확인하는 방법에 대해 일러준다.
소개한다. 설명한다. 어떤 것으로 할까요?

2022-02-06 11:41 UTC, lisohh commented on content/ui-testing-handbook/react/ko-kr/interaction-testing.md
> +상태가 올바르게 업데이트 되었는지 확인한다.
앗 넵

2022-02-06 11:42 UTC, lisohh commented on content/ui-testing-handbook/react/ko-kr/interaction-testing.md
> +우리는 Testing Library을 이용해 스토리를 올리고 렌더링하는 테스트를 성공적으로 작성했다.그 후 시뮬레이션된 유저 동작을 적용하고 해당 컴포넌트의 상태가 정확히 업데이트 되었는지 확인한다.
띄어쓰기 수정하겠습니다.

2022-02-06 11:42 UTC, lisohh commented on content/ui-testing-handbook/react/ko-kr/interaction-testing.md
> +해보자. `InboxScreen.test.js`파일을 만들고 첫 번째 테스트를 작성해라.위의 예와 같이 우리는 이러한 테스트에 스토리를 가져와서 Testing-Library에 잇는 'render'기능을 이용해 쌓는다.
띄어쓰기 수정하겠습니다.

2022-02-06 12:00 UTC, twinstae requested changes
일단 1/3 리뷰했어요!

2022-02-06 12:05 UTC, lisohh commented on content/ui-testing-handbook/react/ko/interaction-testing.md
> +스위치를 눌러도,전등이 켜지지 않는다. 전구가 타버린 것일 수도, 혹은 배선 결함이었을 수도 있다.
띄웠습니다.

2022-02-06 12:05 UTC, lisohh commented on content/ui-testing-handbook/react/ko/interaction-testing.md
> +App들도 마찬가지다. 표면에서 사용자들이 보고 상호작용하는 것은 UI이다. 표면 아래에서는, UI가 연결되어 있어 정보와 이벤트의 흐름이 잘 연결되도록 한다.
오 네 둘 다 그렇게 할게요.

2022-02-06 12:06 UTC, lisohh commented on content/ui-testing-handbook/react/ko/interaction-testing.md
> +페이지와 같은 복잡한 UI를 만들수록
넵

2022-02-06 12:07 UTC, lisohh commented on content/ui-testing-handbook/react/ko/interaction-testing.md
> +이 장에서는 독자들에게 컴퓨터를 사용하여 사용자 상호 작용을 시뮬레이션하고 확인하는 방법에 대해 일러준다.
네 생략하겠습니다.

2022-02-06 12:09 UTC, lisohh commented on content/ui-testing-handbook/react/ko/interaction-testing.md
> +컴포넌트의 주요 작업은 prop들을 받아서 한 조각의 UI으로 렌더링하는 것이다. 더 복잡한 컴포넌트들은 application의 상태를 추적하기도 하며 application의 동작들을 컴포넌트 트리에 전달한다.
내려준다보다는 전달한다가 전해주는 의미가 있어서 좋을 거 같다고 생각했습니다. 임무나 업무로 하려다가 좀 더 부드러운 말이 좋을 것 같아 작업이라고 했어요. 이 두 부분은 상의를 해보는 게 좋겠네요.

2022-02-06 12:09 UTC, lisohh commented on content/ui-testing-handbook/react/ko/interaction-testing.md
> +예를 들어,컴포넌트는 초기 상태를 가지고 시작한다.
넵

2022-02-06 12:10 UTC, lisohh commented on content/ui-testing-handbook/react/ko/interaction-testing.md
> +user가 입력창에 무언가를 타이핑하거나 버튼을 클릭할 때, 이런 동작은 app안의 event를 유발한다.
알겠습니다

2022-02-06 12:15 UTC, perfumelim commented on content/ui-testing-handbook/react/ko/interaction-testing.md
> +2.  **🤖 실행:** 컴포넌트를 렌더링하고 인터랙션을 시뮬레이션 한다.
저도 이 부분 상호작용이라고 해야할지 음차로 할지 고민됐어요..

2022-02-06 12:16 UTC, lisohh commented on content/ui-testing-handbook/react/ko/interaction-testing.md
> +`InboxScreen`에서, 사용자는 업무를 고정시키기 위해 별 아이콘을 클릭할 수 있다. 혹은 checkbox를 클릭해 업무를 저장할 수 있다. 시각적 테스트들은 컴포넌트가 이러한 모든 상태 안에서 올바르게 보이는지 확인한다.또한 우리는 UI가 이와 같은 상호 작용에 정확히 응답하는 지 확인해야한다.
todo, task, job. 이 부분은 홍시,토끼,저 셋이 합의를 해야 하는군요.
respond도 오늘 합의해봐야겠습니다.

2022-02-06 12:16 UTC, lisohh commented on content/ui-testing-handbook/react/ko/interaction-testing.md
> +2.  **🤖 실행:** 컴포넌트를 렌더링하고 인터랙션을 시뮬레이션 한다.
일단 다른 것들과 통일되도록 '상호작용'으로 고쳤습니다.

2022-02-12 11:22 UTC, perfumelim commented
고생하셨습니다  🍊 🧡

2022-03-12 08:17 UTC, lisohh commented on content/ui-testing-handbook/react/ko-kr/interaction-testing.md
> +`InboxScreen`에서, 사용자는 업무를 고정시키기 위해 별 아이콘을 클릭할 수 있습니다. 혹은 checkbox를 클릭해 업무를 보관할 수 있습니다. 시각적 테스트들은 컴포넌트가 이러한 모든 상태 안에서 올바르게 보이는지 확인합니다. 또한 우리는 UI가 이와 같은 상호 작용에 정확히 응답하는지 확인해야합니다.
저는 북마크는 저장의 의미도 있다고 생각이 들어요. 이부분은 11일에 얘기나눕시당 :)

2022-03-12 08:17 UTC, lisohh commented on content/ui-testing-handbook/react/ko-kr/interaction-testing.md
> +상호 작용 테스트 워크플로우(workflow)는 다음과 같습니다.
아핫 네!

2022-03-12 08:26 UTC, lisohh commented on content/ui-testing-handbook/react/ko-kr/interaction-testing.md
> +1.  **📝 구성:** 컴포넌트를 분리해 적절한 prop를 주고 초기상태로 만들어보자.
앗 바꿀게요 그러네요~~

2022-03-12 08:27 UTC, lisohh commented on content/ui-testing-handbook/react/ko-kr/interaction-testing.md
> + 그게 바로 Adobe, Twilio, Gatsby 그리고 더 많은 회사의 팀들이 [Testing-Library](https://testing-library.com/)를 사용하는 이유입니다.[Testing-Library]은 렌더링된 결과물을 평가할 수 있게 합니다.
[]괄호 말씀하시는 걸까요?

2022-03-12 08:27 UTC, lisohh commented on content/ui-testing-handbook/react/ko-kr/interaction-testing.md
> +앞 장에서는 'InboxScreen.stories.js' 파일에 'InboxScreen' 구성 요소의 모든 사용 사례를 목록으로 작성했습니다. 이를 통해 개발 중 모습을 확인하고 비주얼 테스트를 통해 regression(회귀,퇴행..)을 포착할 수 있었습니다.
감사합니닷

2022-03-12 09:09 UTC, lisohh commented on content/ui-testing-handbook/react/ko-kr/interaction-testing.md
> +테스트 사례로 스토리를 작성할 때, 어떤 형태의 주장도 층층이 쌓일 수 있습니다. 한번 해봅시다. `InboxScreen.test.js`파일을 만들고 첫 번째 테스트를 작성해봅시다. 위의 예와 같이 우리는 이러한 테스트에 스토리를 가져와서 Testing-Library에 잇는 'render'기능을 이용해 쌓습니다.
그러면 assertion에 대한 설명을 주석으로 달아놔도 좋을 거 같네요! 완전 열심히 찾아보시는 향수님 감사합니다 하뚜
그리구 can be layered on top은 스토리 위에 올라갈 수 있다는 의미가 맞는 거 같아요 일단 고 부분만 바꿔놓겠습니다!

2022-03-12 09:12 UTC, lisohh commented on content/ui-testing-handbook/react/ko-kr/interaction-testing.md
> +그 'it' 블록은 우리의 테스트를 나타낸다.먼저 컴포넌트를 렌더링하고 데이터를 가져올 때까지 기다린 후 특정 작업을 찾아 핀 버튼을 클릭합니다. 확언 문장은 고정된 상태가 업데이트되었는지 확인합니다. 마지막으로 `afterEach` 블록이 테스트 중에 마운트된 리액트 트리들을 마운트 해제하여 정리합니다.
넵넵

2022-03-12 09:16 UTC, lisohh commented on content/ui-testing-handbook/react/ko-kr/interaction-testing.md
> +복잡한 구성요소들은 테마 프로바이더나 컨텍스트와 같은 외부 의존성에 의존해 글로벌 데이터를 공유합니다. Storybook은 [decorators](https://storybook.js.org/docs/react/writing-stories/decorators)을 사용해 스토리를 감싸고 그러한 기능을 제공합니다. 모든 구성과 함께 스토리를 가져오려면 [@s
앗 그렇군요! 넵 그럼 함수이름 그대로 쓰겠습니다. 번역해주신 문장이 더 매끄러운거 같아요 그대로 바꾸겠습니다~

2022-03-12 09:17 UTC, lisohh commented on content/ui-testing-handbook/react/ko-kr/interaction-testing.md
> +우선 글로벌 데코레이터들을 모두 등록해야합니다.
위를 전역으로 바꿨으니 일단 밑에도 통일할게요. 전역 데코레이터라고 하면 데코레이터도 바꿔야 좀 더 나을 거 같다는 생각이 들어요

2022-03-12 10:52 UTC, lisohh commented on content/ui-testing-handbook/react/ko-kr/interaction-testing.md
> +MSW addon을 위한 데코레이터입니다. 두 데코레이터 모두 [`.storybook/preview`](https://github.com/chromaui/ui-testing-guide-code/blob/interaction-testing/.storybook/preview.js) file 파일을 통해 구성됩니다.
오매

2022-03-12 10:54 UTC, lisohh commented on content/ui-testing-handbook/react/ko-kr/interaction-testing.md
> +다음 장에서는 스토리들의 이동성을 활용해 접근성을 간소화하는 방법을 보여주려 합니다.
맞아요 ㅠㅠ 접근성을 간소화한다니

2022-03-12 10:55 UTC, lisohh reviewed
향수님 코멘트 확인

2022-03-12 10:59 UTC, lisohh commented on content/ui-testing-handbook/react/ko-kr/accessibility-testing.md
> +미국에 있는 [성인의 26%](https://www.cdc.gov/ncbddd/disabilityandhealth/infographic-disability-impacts-all.html)는 적어도 하나의 장애를 가지고 있습니다. 접근성을 개선하면, 현재 그리고 미래의 고객들에게 아주 커다란 영향을 미칩니다. 또한 접근성은 법적인 요건이기도 합니다.
넵 !

2022-03-12 11:00 UTC, lisohh commented on content/ui-testing-handbook/react/ko-kr/accessibility-testing.md
> +그것이 바로 현재 많은 회사들이 자동과 수동 테스팅을 함께 사용하는 이유입니다. 자동화는 개발자들이 크게 힘쓰지 않으며 일반적인 접근성 문제를 파악합니다.
오 좋아요~ '자동화는 개발자들이 크게 공들이지 않아도 일반적인 접근성 문제를 파악합니다.'로 변경해볼게요.

2022-03-12 11:03 UTC, lisohh commented on content/ui-testing-handbook/react/ko-kr/accessibility-testing.md
> +시작하기 전에, 일반적인 장애의 유형을 살펴보자 - 시각, 청각, 이동성, 인지, 언어 그리고 신경학적인.
ㅠㅠ ㅋㅋㅋ 어미는 바꾸지만 번역투는 어떻게 해야할지 모르겠네요,,

2022-03-12 11:05 UTC, lisohh commented on content/ui-testing-handbook/react/ko-kr/accessibility-testing.md
> +-> 여기서 against를 '대해'라고 할지 '반해'라고 할지 고민입니다.
오 일단 그렇게 바꿔놓을게요. 그게 더 맞는 것 같아요!

2022-03-12 11:06 UTC, lisohh commented on content/ui-testing-handbook/react/ko-kr/accessibility-testing.md
> +const longTitleString = `This task's name is absurdly large. In fact, I think if I keep going I might end up with content overflow. What will happen? The star that represents a pinned task could have
앗 넵!

2022-03-12 11:06 UTC, lisohh commented on content/ui-testing-handbook/react/ko-kr/accessibility-testing.md
> +addon이 어떻게 두개의 위반을 발견했는지 봅시다. 첫 번째,**“전경색과 배경색의 대비가 WCAG 2 AA 대비율 임계값을 충족하는지 확인하기”**는 '보관' 상태에 한정됩니다. 본질적으로 그것은 글과 배경의 대비가 충분하지 않음을 의미합니다. 텍스트 색상을 '회색.400'에서 '회색.600'으로 약간 더 어두운 회색으로 변경함으로써 이 문제를 해결할
네 그게 나을 것 같아요 ㅎ

2022-03-12 11:07 UTC, lisohh reviewed
향수님 accessbility-testing 리뷰 확인

2022-03-12 14:45 UTC, lisohh reviewed
이 글도 리뷰 해주세요~ @twinstae @perfumelim

2022-03-13 11:24 UTC, lisohh reviewed
변경해야할 사항들 찾아냄

2022-03-13 11:24 UTC, lisohh commented on content/ui-testing-handbook/react/ko/interaction-testing.md
> +'it' 블록은 우리의 테스트를 나타냅니다.먼저 컴포넌트를 렌더링하고 데이터를 가져올 때까지 기다린 후 특정 작업을 찾아 핀 버튼을 클릭합니다. 확언 문장은 고정된 상태가 업데이트되었는지 확인합니다. 마지막으로 `afterEach` 블록이 테스트 중에 마운트된 리액트 트리들을 마운트 해제하여 정리합니다.
앗 이것도 assertion으로 바꿔야겠어요 확언->assertion

2022-03-13 11:24 UTC, lisohh commented on content/ui-testing-handbook/react/ko/interaction-testing.md
> +'it' 블록은 우리의 테스트를 나타냅니다.먼저 컴포넌트를 렌더링하고 데이터를 가져올 때까지 기다린 후 특정 작업을 찾아 핀 버튼을 클릭합니다. 확언 문장은 고정된 상태가 업데이트되었는지 확인합니다. 마지막으로 `afterEach` 블록이 테스트 중에 마운트된 리액트 트리들을 마운트 해제하여 정리합니다.
여기 pin button이라는 말이 등장해서 북마크대신 pin을 쓰는게 맞는 거 같아요

2022-03-13 11:56 UTC, perfumelim commented on content/ui-testing-handbook/react/ko/accessibility-testing.md
> +대부분의 기존 테스트 환경과 통합되므로 [Axe library](https://github.com/dequelabs/axe-core)를 사용하는 팀이 많습니다. 예를 들어, the [Twilio Paste](https://github.com/twilio-labs/paste) 팀은 [jest-axe integration](https://github.com/
Twilio Paste 앞에 the 지워주세요 ~

2022-03-13 11:56 UTC, perfumelim commented on content/ui-testing-handbook/react/ko/accessibility-testing.md
> +## 접근성 테스팅 workflow
스프레드 시트 보면 작업흐름으로 번역하기로 되어 있었어요 ㅎㅎ! 하단의 workflow들도 수정해주세요~

2022-03-13 11:56 UTC, perfumelim commented on content/ui-testing-handbook/react/ko/accessibility-testing.md
> +두 번째 위반인 **“`<li>` 요소가 의미있게 사용되도록 하기”**는 DOM 구조가 잘못되었음을 나타냅니다. 작업 컴포넌트는 `<li>` 요소를 렌더링합니다. 하지만 스토리안에서 `<li>` 요소가 자신을 sementic하게 만들어주는  `<ul>` 로 감싸지지 않았습니다. 이 스토리들은 작업 컴포넌트를 위한 것입니다. `<ul>`은 사실 TaskLi
작업 스토리로 번역하지 않고 Task를 그대로 써야 하지 않을까요?

2022-03-13 11:56 UTC, perfumelim commented on content/ui-testing-handbook/react/ko/accessibility-testing.md
> +컴포넌트는 상호의존적이며 - 한 컴포넌트의 변화가 사고로 다른 컴포넌트를 파괴할 수 있습니다. 접근성 위반이 발생하지 않도록 하려면, 변경사항을 병합하기 전에 모든 컴포넌트에 Axe를 실행해야 합니다.
by accident가 사고라는 뜻보다는 의도와는 다르게~ 이런 의미로 해석하는 게 더 자연스러울 것 같네요..?

2022-03-13 13:29 UTC, lisohh commented on content/ui-testing-handbook/react/ko/interaction-testing.md
> +컴포넌트의 주요 작업은 prop들을 받아서 한 조각의 UI으로 렌더링하는 것이다. 더 복잡한 컴포넌트들은 application의 상태를 추적하기도 하며 application의 동작들을 컴포넌트 트리에 전달한다.
임무만 바꿀게요~

2022-03-13 13:49 UTC, lisohh commented on content/ui-testing-handbook/react/ko/accessibility-testing.md
> +컴포넌트는 상호의존적이며 - 한 컴포넌트의 변화가 사고로 다른 컴포넌트를 파괴할 수 있습니다. 접근성 위반이 발생하지 않도록 하려면, 변경사항을 병합하기 전에 모든 컴포넌트에 Axe를 실행해야 합니다.
우연히로 바꿀게요~

2022-03-13 13:54 UTC, perfumelim approved these changes

2022-03-13 13:54 UTC, perfumelim commented on content/ui-testing-handbook/react/ko/accessibility-testing.md
> +const longTitleString = `이 일정의 이름은 어마어마하게 길어요. 지금처럼 계속 길어지다가는 내용이 넘칠 수도 있을 것 같습니다. 이렇게 되면 무슨 일이 일어날까요? 고정된 일정을 나타내는 별 모양 아이콘에 텍스트가 겹칠 수도 있습니다. 아니면 아이콘에 도달했을 때 텍스트가 갑자기 잘릴 수도 있겠죠. 부디 그렇지 않기를 바랍니다!`
바꿔주셨군요 좋습니다

2022-03-13 13:58 UTC, merged